function wave = generateExcitingTorque(params)
wave = struct();

% Load hydrodynamic data
[wave.w,wave.Kexc] = getExcited;
        % This was generated by capytaine and assumes the flap can only
        % rotate about the hinge point (as opposed to wecsims
        % documentation, which calculates hydro coefficients assuming the
        % body can move in all degrees of freedom and them adds constraints
        % later)

% Generate Wave Spectrum
wave.spectrum = getSpectrum(wave.w,...
    params.simu.peakPeriod,...
    params.simu.sigWaveHeight);

% Calculate average wave resource
wave.avePower = calculateWavePower(params,wave);

wave.torque = getTorqueTimeSeries(params,wave);

% Regular Waves
% TexcMag = 2e6;
% [~,rampStartInd] = min(abs(t-params.rampTime));
% ramp = 0.5*(1+cos(pi+pi*t/params.rampTime)).*(t<params.rampTime) + (t>=params.rampTime);
% Texc = TexcMag*sin(t*2*pi/params.period).*ramp;


end

function [w,Kexc] = getExcited
filename = 'oswec_new2.nc';
% information vector (gives names of variables)
info = ncinfo(filename);

% Get frequency
w = ncread(filename,'omega');

% Excitation Force
tmp = ncread(filename,'excitation_force');

% Gain
Kexc = squeeze(tmp(1,1,:,1)) + 1i*squeeze(tmp(1,1,:,2));

% % Plot 
% figure
% subplot(211)
% semilogx(w,20*log10(abs(Kexc)))
% grid, xlim([.16, 5])
% 
% subplot(212)
% semilogx(w,angle(Kexc)*180/pi)
% grid, xlim([.16, 5])
end