function wave = generateExcitingTorque(params)
wave = struct();

% Load hydrodynamic data
wave.BEMdata = load('hydroCoeffs.mat');
        % This was generated by capytaine and assumes the flap can only
        % rotate about the hinge point (as opposed to wecsims
        % documentation, which calculates hydro coefficients assuming the
        % body can move in all degrees of freedom and them adds constraints
        % later)

% Generate Wave Spectrum
wave.spectrum = getSpectrum(wave.BEMdata,...
    params.simu.peakPeriod,...
    params.simu.sigWaveHeight);

% Calculate average wave resource
wave.avePower = calculateWavePower(params,wave);

wave.torque = getTorqueTimeSeries(params,wave);

% Regular Waves
% TexcMag = 2e6;
% [~,rampStartInd] = min(abs(t-params.rampTime));
% ramp = 0.5*(1+cos(pi+pi*t/params.rampTime)).*(t<params.rampTime) + (t>=params.rampTime);
% Texc = TexcMag*sin(t*2*pi/params.period).*ramp;


end