% Code to run this function:
% Tp = 8;
% Hs = 3;
% rampTime  = 5*Tp;
% finalTime = 100*Tp;
% dt = .01;
% 
% out = IrregularWaves(Tp,Hs,rampTime,finalTime,dt);

function out = IrregularWaves(Tp,Hs,rampTime,finalTime,dt)
% Author: Jackson Wills
% Date made: Feb 23, 2026

% Description: Generate a time series of excitation torque for the flap
    % from the wecSIM example files.

% Code dependencies:
    % Spectrum (function defined in this file)
    % CalculateWaveNumber (function defined in this file)
    % CalculateWavePower (function defined in this file)
    % hydroCoeffs.mat
        % This was generated by capytaine and assumes the flap can only
        % rotate about the hinge point (as opposed to wecsims
        % documentation, which calculates hydro coefficients assuming the
        % body can move in all degrees of freedom and them adds constraints
        % later)

% Generate time vector
time = (0:dt:finalTime)';

% Generate ramp function
ramp = .5*(1+cos(pi + pi/rampTime*time)).*(time<rampTime) + (time>=rampTime);

% Generate Wave Spectrum
waves = Spectrum(Tp,Hs);

% Define constants
g = 9.81; rho = 1023;

% Randomly assign phases to each frequencies
rng(1) % Sets random seed for repeatability
phase = 2*pi*rand(size(waves.omega));

% Calculate delta omega, the change in frequency
dw = [0,diff(waves.omega)];

% Load hydrodynamic data
load hydroCoeffs.mat

% Interpolate from the frequencies used in capytaine to the ones we want to
% use here
ex_re = squeeze(hydro.ex_re(5,1,:));
ex_im = squeeze(hydro.ex_im(5,1,:));

% Clean the real data
    % the first few entries in this are infinite, but they should be zero
ex_re(~isfinite(ex_re))=0;

% Put together the real and imaginary components and dimensionalize
F = transpose((ex_re+ex_im*1i)) * rho*g;

% Put it all together to get the excitation torque
torqueExcitation = ramp.* real(sum( exp(1i*(time*waves.omega+phase)) .* (F.*sqrt(2*waves.spectrum.*dw)) ,2));

% Plot Torque
    % figure, plot(time,torqueExcitation)

% Output results
out = struct();
out.time = time;
out.Texc = torqueExcitation;
out.waveInfo = waves;
out.F = F;
end

function out = Spectrum(Tp,Hs)
% Author: Jackson Wills
% Date made: Feb 23, 2026

% Description: Generate Pierson-Moskowitz Spectrum and the average wave
% resource available.

% Code dependencies:
    % CalculateWaveNumber (function defined in this file)
    % CalculateWavePower (function defined in this file)


% Define frequencies to consider
omegaMin = .04; %rad/s
omegaMax = 20; % rad/s
omegaNum = 500; % number of frequencies considered
omegaVals = linspace(0.04,20,500);

% Pierson-Moskowitz Spectrum for fully develped sea states
B = 5/(4*Tp^4);
A = B*Hs^2/4;
f = omegaVals/(2*pi); % Frequency [Hz]
fSpectrum = A./(f.^5).*exp(-B./f.^4);
spectrum = fSpectrum./(2*pi); 

% Wave Power
power = CalculateWavePower(spectrum,omegaVals);

% Plot spectrum
figure, semilogx(f,fSpectrum), grid, xlabel('Frequency [Hz]'), ylabel('Spectrum [m^2/Hz]')

% output values
out = struct();
out.omega = omegaVals;
out.spectrum = spectrum;
out.Tp = Tp;
out.Hs = Hs;
out.power = power;
end

function power = CalculateWavePower(spectrum,omegaVals)
g = 9.81; rho = 1023;
dw = [0,diff(omegaVals)];
waterDepth = 8; % m

waveNumber = CalculateWaveNumber(omegaVals,waterDepth);

% Calculate Wave Power
power = sum((1/2)*rho*g*spectrum.*dw.*sqrt(g./waveNumber.*tanh(waveNumber.*waterDepth)).*(1 + 2.*waveNumber.*waterDepth./sinh(2.*waveNumber.*waterDepth)));

end

function waveNumber = CalculateWaveNumber(omegaVals,waterDepth)
waveNumber = NaN(size(omegaVals));
for omegaInd = 1:length(omegaVals)
    omega = omegaVals(omegaInd);
    g = 9.81;

    % Deep water approximation, initial guess
    k = omega.^2./g;

    % Iterate for shallow and intermediate water, full dispersion relationship
    if isfinite(waterDepth)
        for i = 1:100
            k = omega.^2./g./tanh(k.*waterDepth);
        end
    end
    waveNumber(omegaInd) = k; 
end

% plot
% figure, plot(omegaVals,waveNumber,omegaVals,omegaVals.^2./g)
% legend('Shallow water','Deep water'), grid
% xlabel('Frequency [Hz]'), ylabel('wave Number [1/m]')

end